force-app/main/default/objects/Campaign/fields/gc_event_id__c.field-meta.xml
<CustomField>
    <fullName>gc_event_id__c</fullName>
    <description>Event ID number will be assigned by GiveCentral and is not editable.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique event ID number will be assigned by GiveCentral for this campaign and is not editable.</inlineHelpText>
    <label>GC Event ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Merchant_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Merchant ID number assigned to your nonprofit organization for transacting debit and credit card payments.</description>
    <inlineHelpText>The unique merchant ID# provided to your organization by GiveCentral for processing credit and debit card payments.</inlineHelpText>
    <label>Merchant ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Merchant_Id__c.Type__c</field>
            <operation>equals</operation>
            <value>CC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Merchant_Id__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/minimumAmounts__c.field-meta.xml
<CustomField>
    <fullName>minimumAmounts__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>A suggested minimum donation amount that can be displayed on available donor-facing forms for this campaign.</inlineHelpText>
    <label>Minimum Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/suggestedAmount__c.field-meta.xml
<CustomField>
    <fullName>suggestedAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>A suggested donation amount for this campaign that will appear on certain donor-facing forms.</inlineHelpText>
    <label>Suggested Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Id__c/Merchant_Id__c.object-meta.xml
<CustomObject>
    <label>Merchant ID</label>
    <nameField>
        <label>Merchant ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Id__c/fields/MID__c.field-meta.xml
<CustomField>
    <fullName>MID__c</fullName>
    <label>MID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncEventCalloutSync.cls
public class SyncEventCalloutSync {
    @Future(callout=true)
	public static Void EventDataCallout(List<Id> idVal) {
        String ColumnName = 'Id,gc_event_id__c,Name,StartDate,EndDate,Type,ActualCost,Status,BudgetedCost,minimumAmounts__c,suggestedAmount__c,Merchant_Id__c';
        sObject DataVal = CommonClass.GetQueryData('Campaign',ColumnName,idVal[0]);
        Campaign CampaignData = (Campaign)DataVal;
        
        String MIDVal = CampaignData.Merchant_Id__c;
        Merchant_Id__c[] merchantData = [SELECT Id,MID__c FROM Merchant_Id__c where Id=:MIDVal];
        String MerchantId = string.valueOf(merchantData.get(0).MID__c);
        string minimumAmounts = (string.valueOf(CampaignData.minimumAmounts__c) == null) ? '' : string.valueOf(CampaignData.minimumAmounts__c);
        string suggestedAmount = (string.valueOf(CampaignData.suggestedAmount__c) == null) ? '' : string.valueOf(CampaignData.suggestedAmount__c);		
        
        String URL;
        String eventid='';
        String EventType='';
        if(string.valueOf(CampaignData.gc_event_id__c) != null && string.valueOf(CampaignData.gc_event_id__c) != ''){
            URL = Label.ApiCallUrl+'intregation/saveEventsDetails/'+string.valueOf(CampaignData.gc_event_id__c);
            eventid = ',"eventid":"'+string.valueOf(CampaignData.gc_event_id__c)+'"';
            EventType = '"sfEventType":"event",';
        }else{
            URL = Label.ApiCallUrl+'intregation/saveEventsDetails';
            EventType = '"sfEventType":"event",';
        }
        //String CampString = '{"Id":"'+idVal[0]+'","org_id": "'+CommonClass.OrgId()+'","eventTitle":"'+CampaignData.Name+'","eventStartDate":"'+CampaignData.StartDate+'","eventEndDate":"'+CampaignData.EndDate+'","eventType":"'+CampaignData.Type+'","eventFrequency":["Monthly","One-Time","Weekly","Bi-Weekly","Quarterly","Semi-Annually","Annually"],"minimumAmounts":["'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'"],"suggestedAmount":["'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'"],"accountsMerchantId":"'+MerchantId+'","displayOrder":"0","categoryId":"0","eventStatus":"'+CampaignData.Status+'","restrictDonationsBeyondEndDate":"0","sf_api_call":"0"}';

        String CampString = '{'+EventType+' "sfId":"'+idVal[0]+'","org_id": "'+CommonClass.OrgId()+'" '+eventid+',"eventTitle":"'+CampaignData.Name+'","eventStartDate":"'+CampaignData.StartDate+'","eventEndDate":"'+CampaignData.EndDate+'","eventType":"'+CampaignData.Type+'","eventFrequency":["Monthly","One-Time","Weekly","Bi-Weekly","Quarterly","Semi-Annually","Annually"],"minimumAmounts":["'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'","'+minimumAmounts+'"],"suggestedAmount":["'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'","'+suggestedAmount+'"],"accountsMerchantId":"'+MerchantId+'","displayOrder":"0","categoryId":"0","eventStatus":"'+CampaignData.Status+'","restrictDonationsBeyondEndDate":"0","sf_api_call":"0"}';
    	String StringVal= CampString;
        CommonClass.HTTPRequest(StringVal,URL);
    }

}