force-app/main/default/objects/Campaign/fields/Merchant_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Merchant ID number assigned to your nonprofit organization for transacting debit and credit card payments.</description>
    <inlineHelpText>The unique merchant ID# provided to your organization by GiveCentral for processing credit and debit card payments.</inlineHelpText>
    <label>Merchant ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Merchant_Id__c.Type__c</field>
            <operation>equals</operation>
            <value>CC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Merchant_Id__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/minimumAmounts__c.field-meta.xml
<CustomField>
    <fullName>minimumAmounts__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>A suggested minimum donation amount that can be displayed on available donor-facing forms for this campaign.</inlineHelpText>
    <label>Minimum Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/suggestedAmount__c.field-meta.xml
<CustomField>
    <fullName>suggestedAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>A suggested donation amount for this campaign that will appear on certain donor-facing forms.</inlineHelpText>
    <label>Suggested Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonorPaymentMethod__c/DonorPaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Donor Payment Method</label>
    <nameField>
        <label>Donor Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donor Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonorPaymentMethod__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>DonorPaymentMethod</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DonorPaymentMethod__c/fields/donor_payment_method_id__c.field-meta.xml
<CustomField>
    <fullName>donor_payment_method_id__c</fullName>
    <externalId>true</externalId>
    <label>donor payment method id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonorPaymentMethod__c/fields/donorId__c.field-meta.xml
<CustomField>
    <fullName>donorId__c</fullName>
    <label>donorId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonorPaymentMethod__c/fields/FourDegit__c.field-meta.xml
<CustomField>
    <fullName>FourDegit__c</fullName>
    <label>FourDigit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonorPaymentMethod__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merchant_Id__c/Merchant_Id__c.object-meta.xml
<CustomObject>
    <label>Merchant ID</label>
    <nameField>
        <label>Merchant ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Id__c/fields/MID__c.field-meta.xml
<CustomField>
    <fullName>MID__c</fullName>
    <label>MID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Id__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/DonorPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>DonorPaymentMethod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DonorPaymentMethod__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.npe03__Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DonorPaymentMethod__c</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Status__c.field-meta.xml
<CustomField>
    <fullName>Record_Status__c</fullName>
    <label>Record Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityClassTest.cls
@Istest
public class OpportunityClassTest {
	@Istest 
	static void testCallout(){
        List<sObject> records2 = new List<sObject>();
        
        records2.add(new Contact(firstname='TestFirstApi1',lastname='LastMiddle',Email='TestEmailApi@gmail.com'));
        insert records2;
        List<Id> ContactId = new List<Id>();
        Contact ContactVal;
        ContactVal = [SELECT Id FROM Contact];
        ContactId.add(ContactVal.Id);
        
        List<sObject> records3 = new List<sObject>();
        records3.add(new DonorPaymentMethod__c(Name='PMTTest1',Contact__c=ContactVal.Id,FourDegit__c='xxx1111',donor_payment_method_id__c=1111,donorId__c=1234));
        insert records3;
        DonorPaymentMethod__c DonorPaymentMethodVal;
        DonorPaymentMethodVal = [SELECT Id FROM DonorPaymentMethod__c];
        
        List<sObject> records5 = new List<sObject>();
        records5.add(new Merchant_Id__c(Name='Not Applicable',MID__c='46',Type__C='CC'));
        insert records5;
        Merchant_Id__c MerchantVal;
        MerchantVal = [SELECT Id FROM Merchant_Id__c];
        
        List<sObject> records4 = new List<sObject>();
        records4.add(new Campaign(Name='EventName1',Type='Pledged Events',Status='Active',StartDate=date.valueOf('2019-05-22'),EndDate=date.valueOf('2022-07-22'),minimumAmounts__c=decimal.valueOf('1'),suggestedAmount__c=decimal.valueOf('2'),Merchant_Id__c=MerchantVal.Id));
        insert records4;
        Campaign CampaignVal;
        CampaignVal = [SELECT Id FROM Campaign];
       
        List<sObject> records = new List<sObject>();
        List<Id> recordsRecc = new List<Id>();
        records.add(new npe03__Recurring_Donation__c(Name='Rec123',npe03__Contact__c=ContactVal.Id,npe03__Next_Payment_Date__c=date.valueOf('2019-05-22'),npe03__Installment_Period__c='Monthly',npe03__Amount__c=11,npe03__Installments__c=1,npe03__Schedule_Type__c='Multiply By',npe03__Recurring_Donation_Campaign__c=CampaignVal.Id,DonorPaymentMethod__c=DonorPaymentMethodVal.Id));
        insert records;
		npe03__Recurring_Donation__c RecVal;
        npe03__Recurring_Donation__c RecValue;
        RecVal = [SELECT Id FROM npe03__Recurring_Donation__c where Name = 'Rec123'];

        Opportunity OppValue;
        OppValue = [SELECT ID,Record_Status__c FROM Opportunity where npe03__Recurring_Donation__c=:RecVal.Id];
        
        Test.starttest();
        
        Test.setMock(HttpCalloutMock.class, new OpportunityClassHttpCallout());
        OpportunityClass.OpportunityData(OppValue.Id);
        System.assertEquals(200, 200);
        
        Test.StopTest();
    }
}