force-app/main/default/objects/Campaign/fields/Merchant_Id__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Merchant ID number assigned to your nonprofit organization for transacting debit and credit card payments.</description>
    <inlineHelpText>The unique merchant ID# provided to your organization by GiveCentral for processing credit and debit card payments.</inlineHelpText>
    <label>Merchant ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Merchant_Id__c.Type__c</field>
            <operation>equals</operation>
            <value>CC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Merchant_Id__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/minimumAmounts__c.field-meta.xml
<CustomField>
    <fullName>minimumAmounts__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>A suggested minimum donation amount that can be displayed on available donor-facing forms for this campaign.</inlineHelpText>
    <label>Minimum Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/suggestedAmount__c.field-meta.xml
<CustomField>
    <fullName>suggestedAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>A suggested donation amount for this campaign that will appear on certain donor-facing forms.</inlineHelpText>
    <label>Suggested Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchant_Id__c/Merchant_Id__c.object-meta.xml
<CustomObject>
    <label>Merchant ID</label>
    <nameField>
        <label>Merchant ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Id__c/fields/MID__c.field-meta.xml
<CustomField>
    <fullName>MID__c</fullName>
    <label>MID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Merchant_Id__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SyncEventToGCTest.cls
@Istest 
public class SyncEventToGCTest {
	@Istest 
	static void testCallout(){
       
        List<sObject> records = new List<sObject>();
        List<sObject> records1 = new List<sObject>();
        
        records1.add(new Merchant_Id__c(Name='Not Applicable',MID__c='46',Type__C='CC'));
        insert records1;
        Merchant_Id__c MerchantVal;
        MerchantVal = [SELECT Id FROM Merchant_Id__c];
        
        records.add(new Campaign(Name='EventName',Type='Pledged Events',Status='Active',StartDate=date.valueOf('2019-05-22'),EndDate=date.valueOf('2022-07-22'),minimumAmounts__c=decimal.valueOf('1'),suggestedAmount__c=decimal.valueOf('2'),Merchant_Id__c=MerchantVal.Id));
        insert records;
        
        List<Id> CampaignId = new List<Id>();
        Campaign CampaignVal;
        CampaignVal = [SELECT Id FROM Campaign];
        CampaignId.add(CampaignVal.Id);
       
        
        Test.starttest();
        Test.setMock(HttpCalloutMock.class, new SyncEventCalloutHttpCallout());
        SyncEventCallout.EventDataCallout(CampaignId);
        System.assertEquals(200, 200);
        Test.StopTest();
    }
}