force-app/main/default/objects/BatchEntry__c/BatchEntry__c.object-meta.xml
<CustomObject>
    <label>NPSPBatchEntry</label>
    <nameField>
        <label>BatchEntry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BatchEntrys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchEntry__c/fields/BatchId__c.field-meta.xml
<CustomField>
    <fullName>BatchId__c</fullName>
    <label>BatchId</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchEntry__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>BatchEntrys</relationshipLabel>
    <relationshipName>BatchEntrys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BatchEntry__c/fields/ChequeNumber__c.field-meta.xml
<CustomField>
    <fullName>ChequeNumber__c</fullName>
    <label>ChequeNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchEntry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>BatchEntrys</relationshipLabel>
    <relationshipName>BatchEntrys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BatchEntry__c/fields/DonationDate__c.field-meta.xml
<CustomField>
    <fullName>DonationDate__c</fullName>
    <label>DonationDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BatchEntry__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>PaymentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BatchEntry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPSPBatch__c/NPSPBatch__c.object-meta.xml
<CustomObject>
    <label>NPSPBatch</label>
    <nameField>
        <label>NPSPBatch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPSPBatchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPSPBatch__c/fields/Batch_NUmber__c.field-meta.xml
<CustomField>
    <fullName>Batch_NUmber__c</fullName>
    <displayFormat>G-{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Batch NUmber</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/NPSPBatch__c/fields/BatchCount__c.field-meta.xml
<CustomField>
    <fullName>BatchCount__c</fullName>
    <label>BatchCount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NPSPBatch__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>NPSPBatchs</relationshipLabel>
    <relationshipName>NPSPBatchs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPSPBatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchAPexController.cls
public class BatchAPexController {
    @AuraEnabled
    public static string CreateBatch(string Name,string ExpectedCount,string description,string amount,string Event_id){   
        string Batchname=Name.stripHtmlTags();
        integer count_batch=integer.valueof(ExpectedCount);
        string descp=description;
        integer amount_data=integer.valueof(amount);
        
        try{
           NPSPBatch__c DataInsert=new NPSPBatch__c (Name=Batchname,Description__c=descp,BatchCount__c=count_batch,Amount__c=amount_data,Campaign__c=Id.valueOf(Event_id));
           insert DataInsert;
           return 'record inserted';
            
        }catch(DmlException e) {
            return e.getMessage();
        }
        
    }
    @AuraEnabled
    /*
    public static List<List<String>> PullBatch(){
        
     	list<NPSPBatch__c> pulldata=new list<NPSPBatch__c>([select Id,Name,Batch_NUmber__c,Description__c,BatchCount__c,Amount__c,CreatedDate,Status__c,campaign__r.name from NPSPBatch__c order by CreatedDate DESC limit 5]);
        List<List<String>> mainarray= new List<List<String>>(); 
        if(pulldata!=null && pulldata.size()>0) {
             for(integer i =0;i< pulldata.size();i++){
                 mainarray.add(new List<String>{pulldata[i].Id, pulldata[i].Name,pulldata[i].Batch_NUmber__c,pulldata[i].Description__c,string.valueOf(pulldata[i].BatchCount__c),string.valueOf(pulldata[i].Amount__c),string.valueOf(pulldata[i].CreatedDate),pulldata[i].Status__c,pulldata[i].campaign__r.name});
             }
         }
         return mainarray;
         
        
    }
*/
     public static List<NPSPBatch__c> PullBatch(){
        
     	list<NPSPBatch__c> pulldata=new list<NPSPBatch__c>([select Id,Name,Batch_NUmber__c,Description__c,BatchCount__c,Amount__c,CreatedDate,Status__c,campaign__r.name from NPSPBatch__c order by CreatedDate DESC]);
         return pulldata;
         
        
    }
    @AuraEnabled
    public static List<NPSPBatch__c> PullBatchContact(){
     	list<NPSPBatch__c> pulldata=new list<NPSPBatch__c>([select Id,Name,Batch_NUmber__c,Description__c,BatchCount__c,Amount__c from NPSPBatch__c]);
        return pulldata;
    }
    @AuraEnabled
    public static List<NPSPBatch__c> checkBatch(string BatchId){
     	list<NPSPBatch__c> pullCheckdata=new list<NPSPBatch__c>([select Id,Name,Batch_NUmber__c,Description__c,BatchCount__c,Amount__c from NPSPBatch__c where Id=:BatchId]);
        return pullCheckdata;
    }
    @AuraEnabled
    public static list<Contact> checkContact(string arrayId){
        String alpha = arrayId;
        List<String> lstAlpha = alpha.split(',');
     	list<Contact> ContactPull=new list<Contact>([select Id from Contact where Id in:lstAlpha]);
        //system.debug(ContactPull);
        return ContactPull;
    }
     @AuraEnabled
    public static list<Account> checkAccount(string arrayId){
        String alpha = arrayId;
        List<String> lstAlpha = alpha.split(',');
     	list<Account> accountpull=new list<Account>([select Id from Account where Id in:lstAlpha]);
        //system.debug(ContactPull);
        return accountpull;
    }
     @AuraEnabled
   // public static string InsertDetaildBatch(string BatchId,string Event,string typedata,string Records,string ChequeNumber,string amount,string donationDate){
   public static string InsertDetaildBatch(string BatchId,string[] Records,string[] Event,string typedata,string[] ChequeNumber,string[] amount,string[] donationDate,string[] paymentmethod){
 		//system.debug('ranbir das');
        /*system.debug('Batchid---'+BatchId);
        system.debug('event---'+Event);
        system.debug('type---'+typedata);
        system.debug('Records---'+Records);
        system.debug('ChequeNumber---'+ChequeNumber);
        system.debug('amount---'+amount);
        system.debug('donationDate---'+donationDate);*/
        integer length_val=Records.size();
           if(length_val>0){
               try {
                   	List<BatchEntry__c> custList = new List<BatchEntry__c>();
                    for(integer i=0;i<length_val;i++){
                        BatchEntry__c obj_list=new BatchEntry__c ();
                        obj_list.BatchId__c= BatchId;
                        obj_list.Contact__c= Id.valueOf(Records[i]);
                        obj_list.Campaign__c= Id.valueOf(Event[i]);
                        obj_list.Type__c= typedata;
                        obj_list.ChequeNumber__c= ChequeNumber[i];
                        obj_list.Amount__c= decimal.valueOf(amount[i]);
                        obj_list.DonationDate__c= Date.valueOf(donationDate[i]);
                        obj_list.PaymentType__c	=paymentmethod[i];
                        custList.add(obj_list);
                    } 
                    insert custList;
                   	return '{"status":200,"message":"Batch Inserted Successfully"}';
                }catch(DmlException e) {
                 	return '{"status":500,"message":"'+e.getMessage()+'"}';   
                }
           }else{
               
           }
       

       return Records[1];
//return 'ff';
    }
}