force-app/main/default/objects/Contact/fields/Donor_Id__c.field-meta.xml
<CustomField>
    <fullName>Donor_Id__c</fullName>
    <inlineHelpText>An identifying number or alphanumeric value for the donor&#39;s offering envelope. Can be shared by other members of the same household, and it is synced to the donor&#39;s GiveCentral profile.</inlineHelpText>
    <label>Donor ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonorPaymentMethod__c/DonorPaymentMethod__c.object-meta.xml
<CustomObject>
    <label>Donor Payment Method</label>
    <nameField>
        <label>Donor Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donor Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonorPaymentMethod__c/fields/donor_payment_method_id__c.field-meta.xml
<CustomField>
    <fullName>donor_payment_method_id__c</fullName>
    <externalId>true</externalId>
    <label>donor payment method id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/DonorPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>DonorPaymentMethod__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DonorPaymentMethod__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.npe03__Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DonorPaymentMethod__c</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>Recurring_Donations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/npe03__Recurring_Donation__c/fields/GcSignupId__c.field-meta.xml
<CustomField>
    <fullName>GcSignupId__c</fullName>
    <externalId>true</externalId>
    <label>GC Signup ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GcScheduleId__c.field-meta.xml
<CustomField>
    <fullName>GcScheduleId__c</fullName>
    <externalId>true</externalId>
    <label>GC Schedule ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GcSignupId__c.field-meta.xml
<CustomField>
    <fullName>GcSignupId__c</fullName>
    <label>GC Signup ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityCalloutSync.cls
public class OpportunityCalloutSync {
	 @Future(callout=true)
	public static Void OpportunityData(List<Id> idVal){
        try{
            system.debug(idVal);
            String AccessToken = GetGcToken.TokenData();
            Opportunity[] OppData=[select Id,GcSignupId__c,GcScheduleId__c,npe03__Recurring_Donation__c,npsp__Primary_Contact__c,Amount,CloseDate from Opportunity where Id =:idVal];
            Contact[] ContactData=[select Id,Donor_Id__c from Contact where Id =:OppData.get(0).npsp__Primary_Contact__c];
            string ReccuringId = string.valueOf(OppData.get(0).npe03__Recurring_Donation__c);
            npe03__Recurring_Donation__c[] CampQuery = [select Id,DonorPaymentMethod__c from npe03__Recurring_Donation__c where Id=:ReccuringId];
            String PMTId = CampQuery.get(0).DonorPaymentMethod__c;
            DonorPaymentMethod__c[] PMTData = [select donor_payment_method_id__c from DonorPaymentMethod__c where Id=:PMTId];
            String PMTDataVal = string.valueOf(PMTData.get(0).donor_payment_method_id__c);
            string donorPaymentScheduleId = string.valueOf(OppData.get(0).GcScheduleId__c);
            string donorEventsId = (string.valueOf(OppData.get(0).GcSignupId__c) == null) ? '' : string.valueOf(OppData.get(0).GcSignupId__c);
            string gcid = (string.valueOf(ContactData.get(0).Donor_Id__c) == null) ? '' : string.valueOf(ContactData.get(0).Donor_Id__c);
			string amount = (string.valueOf(OppData.get(0).Amount) == null) ? '' : string.valueOf(OppData.get(0).Amount);
			string dateVal = (string.valueOf(OppData.get(0).CloseDate) == null) ? '' : string.valueOf(OppData.get(0).CloseDate);
            
            String paymentScheduleId;
            if(donorPaymentScheduleId!=Null){
                
            }else{
                paymentScheduleId = '"donorPaymentScheduleId":"'+donorPaymentScheduleId+'"';
            }
            
            String PostString='{"sfEventType":"editPaymentSchedule","sfId":"'+idVal[0]+'","org_id": "'+CommonClass.OrgId()+'","donorEventsId":"'+donorEventsId+'","editAllSchedule":"false","gcid":"'+gcid+'","amount":"'+amount+'",'+paymentScheduleId+',"date":"'+dateVal+'","donorPaymentMethodId":"'+PMTDataVal+'"}';
            
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint(Label.UpdateOpp);
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setHeader('Authorization', 'Bearer '+AccessToken);  
            req.setBody(PostString);
            HttpResponse ResCreate = http.send(req);
            string strRes=ResCreate.getBody();
            JSONParser parserResult =JSON.createParser(strRes);
            system.debug(PostString);
            system.debug(ResCreate);
            system.debug(strRes);
            String valRes = String.valueOf(ResCreate.getStatusCode()); 
        }catch(exception e){
            system.debug(String.valueOf(e));
        }
        
    }
}