force-app/main/default/objects/Contact/fields/Donor_Id__c.field-meta.xml
<CustomField>
    <fullName>Donor_Id__c</fullName>
    <inlineHelpText>An identifying number or alphanumeric value for the donor&#39;s offering envelope. Can be shared by other members of the same household, and it is synced to the donor&#39;s GiveCentral profile.</inlineHelpText>
    <label>Donor ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The donor&#39;s username for logging in to their GiveCentral profile. Email format is recommended.</inlineHelpText>
    <label>GC User ID</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MergeContactTest.cls
@Istest
public class MergeContactTest {
	@Istest 
	static void testMethodMerge(){
        Test.starttest();
        /*
            List<sObject> records2 = new List<sObject>(); 
            records2.add(new Contact(firstname='TestFirstApi1',lastname='LastMiddle1',Email='TestEmailApi1@gmail.com',Donor_Id__c=123477,User_Id__c='wewe2323'));
            insert records2;
        
            List<Contact> ContactVal = [SELECT Id FROM Contact];
            delete ContactVal;
        */
        
        Contact master = new Contact(firstname='TestFirstApi1',lastname='LastMiddle1',Email='TestEmailApi1@gmail.com',Donor_Id__c=123477,User_Id__c='wewe2323');
        insert master;
        
        Contact[] duplicates = new Contact[]{new Contact(firstname='TestFirstApi1',lastname='LastMiddle1',Email='TestEmailApi1@gmail.com',Donor_Id__c=123477,User_Id__c='wewe2323'), new Contact(firstname='TestFirstApi111',lastname='LastMiddle1',Email='TestEmailApi1@gmail.com',Donor_Id__c=123477,User_Id__c='wewe2323')};
        insert duplicates;
        
        Database.MergeResult[] results = Database.merge(master, duplicates, false);
        
        
        Test.StopTest();
    }
}