force-app/main/default/objects/Contact/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The donor&#39;s username for logging in to their GiveCentral profile. Email format is recommended.</inlineHelpText>
    <label>GC User ID</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPSPBatch__c/NPSPBatch__c.object-meta.xml
<CustomObject>
    <label>NPSPBatch</label>
    <nameField>
        <label>NPSPBatch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPSPBatchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPSPBatch__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>NPSPBatchs</relationshipLabel>
    <relationshipName>NPSPBatchs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/customLookUpController.cls
public class customLookUpController {
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName) {
        system.debug('ObjectName-->' + ObjectName);
        //String searchKey = searchKeyWord + '%';
        
        List < sObject > returnList = new List < sObject > ();
      
        // Create a Dynamic SOQL Query For Fetch Record List with LIMIT 5   
        //String sQuery =  'select id, Name from ' +ObjectName + ' where Name LIKE: searchKey order by createdDate DESC';
        //List < sObject > lstOfRecords = Database.query(sQuery);
        if(searchKeyWord.length()>0){
            String searchQuery='';
            if(ObjectName=='Contact'){
            	searchQuery = 'FIND \'' + searchKeyWord + '\' IN ALL FIELDS RETURNING '+ObjectName +' (id, Name,User_Id__c)';     
            }else{
            	searchQuery = 'FIND \'' + searchKeyWord + '\' IN ALL FIELDS RETURNING '+ObjectName +' (id, Name)';     
            }
        	
            List<List<sObject>> lstOfRecords = search.query(searchQuery);
            
            for (List<SObject> sobjs1 : lstOfRecords) {
                for (SObject sobj1 : sobjs1) {
                    system.debug(sobj1);
                    returnList.add(sobj1);   
                }
            }
        
        //for (sObject obj: lstOfRecords) {
           // returnList.add(obj);
       // }
        return returnList;    
        }else{
            String searchKey = searchKeyWord + '%';
            String sQuery =  'select id, Name from ' +ObjectName + ' where Name LIKE: '+searchKey+' order by createdDate DESC';
            //system.debug(sQuery);
        	List < sObject > lstOfRecords = Database.query(sQuery);
            for (sObject obj: lstOfRecords) {
           	 	returnList.add(obj);
       		}
			return returnList;   
        }
       
    }
    @AuraEnabled
    public static List < sObject > fetchLookUpValuesdefault(String searchKeyWord, String ObjectName) {
         List < sObject > returnList = new List < sObject > ();
        String sQuery =  'select id, Name,Campaign__c from NPSPBatch__c where Id =: searchKeyWord';
        sObject lstOfRecords = Database.query(sQuery);
        NPSPBatch__c getid=(NPSPBatch__c)lstOfRecords;
        Id cmpid=getid.Campaign__c;
        String sQuery1 =  'select id, Name from ' +ObjectName + ' where Id=: cmpid order by createdDate DESC';
        List < sObject > lstOfRecords1 = Database.query(sQuery1);
        for (sObject obj: lstOfRecords1) {
            returnList.add(obj);
        }
        return returnList;  
       
    }
}